sudo: true
services: mongodb
language: node_js
node_js:
  - stable
env:
  - TEST_DIR=client
  - TEST_DIR=server
script: cd $TEST_DIR && npm install && npm test
  # Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
